@hostname = http://localhost:3000
@userId = 6906a62f29799dbaa80d9e32

### Criar usuário
POST {{hostname}}/api/users
Content-Type: application/json

{
    "username": "joãozinho",
    "email": "teste@teste.com",
    "password": "12345678"
}

### Ver todos os usuários
GET {{hostname}}/api/users

### Pegar usuário por id
GET {{hostname}}/api/users/{{userId}}

### Deletar usuário
DELETE {{hostname}}/api/users/{{userId}}

### Checar Email
POST {{hostname}}/api/users/checkemail
Content-Type: application/json

{
    "email": "teste@teste.com"
}