@hostname = http://localhost:5020
@userId = 692a1e974b3c8086923a2da0

### Testar rota básica
GET {{hostname}}

### Criar usuário
POST {{hostname}}/api/users
Content-Type: application/json

{
    "username": "joãozinho",
    "email": "teste@teste.com",
    "password": "12345678"
}

### login
POST {{hostname}}/api/users/login
Content-Type: application/json

{
    "email": "teste@teste.com",
    "password": "12345678" 
}

### logout
POST {{hostname}}/api/users/logout

### Pegar usuário por id
GET {{hostname}}/api/users/{{userId}}

### Deletar usuário
DELETE {{hostname}}/api/users/{{userId}}

### Checar Email
POST {{hostname}}/api/users/checkemail
Content-Type: application/json

{
    "email": "teste@teste.com"
}